server:
  port: 7777

spring:
  application:
    name: dbsample
  datasource:
    url: jdbc:postgresql://localhost:5435/dbsample
    username: dbsample
    password: dbsample
  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yaml
    contexts: development, production
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

